
xcodeproj 'RegisteredLoggingTest'
workspace '../../Demos'

target :RLT_osx do
  platform :osx, '10.9'
  link_with 'RegisteredLoggingTest'
  pod 'CocoaLumberjack', :path => '../../../'
end

use_frameworks!