
xcodeproj 'RegisteredLoggingTest'
workspace '../../Demos'

target :RLT_ios do
  platform :ios, '7.0'
  link_with 'RegisteredLoggingTest'
  pod 'CocoaLumberjack', :path => '../../../'
end

use_frameworks!